apiVersion: v1
kind: Pod
metadata:
  name: {{.Values.pod_name}}
  labels:
    heritage: deis
spec:
  restartPolicy: Never
  containers:
  - name: tests
    image: {{.Values.org}}/workflow-e2e:{{.Values.docker_tag}}
    imagePullPolicy: {{.Values.pull_policy}}
    env:
      - name: DEIS_ROUTER_SERVICE_PORT
        value: "80"
      - name: GINKGO_NODES
        value: "{{.Values.ginkgo_nodes}}"
      - name: JUNIT
        value: "true"
      - name: CLI_VERSION
        value: "{{.Values.cli_version}}"
      # set TEST env variable to run appropriate tests in e2e suite
      - name: TEST
        value: "{{.Values.test}}"
      - name: DEBUG_MODE
        value: "{{.Values.debug_mode}}"
    command: ["/bin/bash"]
    args:
        - -c
        - >
            export DEIS_CONTROLLER_URL=http://deis.$$(getent hosts deis-router | grep -o "^[^ ]*").nip.io;
            export DEIS_ROUTER_SERVICE_HOST=deis.$$(getent hosts deis-router | grep -o "^[^ ]*").nip.io;
            ./docker-test-integration.sh

    volumeMounts:
    - name: artifact-volume
      mountPath: /root
  - name: artifacts
    image: busybox
    imagePullPolicy: Always
    command: ["tail", "-f", "/dev/null"]
    volumeMounts:
    - name: artifact-volume
      mountPath: /root
  volumes:
  - name: artifact-volume
    emptyDir: {}
